source: src
paths:
  data: _data
  collections: ''
  layouts: _includes
  static: ''
  uploads: uploads
  includes: _includes
  pages: ''
inputs:
  - label: Title
    key: title
    input_type: text
  - label: Description
    key: description
    input_type: textarea
collections_config:
  pages:
    path: content/pages
    output: true
    url: /[slug]/
    _enabled_editors:
      - visual
data_config: {}
timezone: Etc/UTC
